<a href="https://colab.research.google.com/github/nagavamshi506-ui/future_interns_task2/blob/main/customer_support_ticket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/customer_support_tickets.csv.zip')
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [3]:
df.shape
df.isnull().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [4]:
df['Resolution']=df['Resolution'].fillna(df['Resolution'].mode()[0])
df['First Response Time']=df['First Response Time'].fillna(df['First Response Time'].mode()[0])
df['Time to Resolution']=df['Time to Resolution'].fillna(df['Time to Resolution'].mode()[0])
df['Customer Satisfaction Rating']=df['Customer Satisfaction Rating'].fillna(df['Customer Satisfaction Rating'].median())

In [5]:
df.isnull().sum()

Ticket ID                       0
Customer Name                   0
Customer Email                  0
Customer Age                    0
Customer Gender                 0
Product Purchased               0
Date of Purchase                0
Ticket Type                     0
Ticket Subject                  0
Ticket Description              0
Ticket Status                   0
Resolution                      0
Ticket Priority                 0
Ticket Channel                  0
First Response Time             0
Time to Resolution              0
Customer Satisfaction Rating    0
dtype: int64

In [6]:
df=df.drop(['Ticket ID','Customer Name','Customer Email','Customer Age','Customer Gender','Product Purchased'],axis=1)

In [7]:
df.head()
df.tail()

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
8464,2021-12-08,Product inquiry,Installation support,My {product_purchased} is making strange noise...,Open,A former wrong interview then heart leg.,Low,Phone,2023-06-01 01:21:19,2023-06-01 17:14:42,3.0
8465,2020-02-22,Technical issue,Refund request,I'm having an issue with the {product_purchase...,Open,A former wrong interview then heart leg.,Critical,Email,2023-06-01 01:21:19,2023-06-01 17:14:42,3.0
8466,2021-08-17,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,Eight account century nature kitchen.,High,Social media,2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,2021-10-16,Product inquiry,Payment issue,I'm having an issue with the {product_purchase...,Closed,We seat culture plan.,Medium,Email,2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,2020-06-01,Billing inquiry,Hardware issue,There seems to be a hardware problem with my {...,Open,A former wrong interview then heart leg.,High,Phone,2023-06-01 01:21:19,2023-06-01 17:14:42,3.0

define all cat_columns

In [36]:
# Define column lists excluding the specific target for each model
cat_cols_p = ['Ticket Channel', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution']
cat_cols_t = ['Ticket Channel', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority']

Text cleaning

convert text to Lower case ,
Remove punctuations ,
Apply tokenization

In [37]:
import string
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
translator=str.maketrans('','',string.punctuation)
for cat in cat_cols_t:
  df[cat]=df[cat].astype(str).str.lower()
  df[cat]=df[cat].str.translate(translator)
  df[cat]=df[cat].apply(word_tokenize)
df.head()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,2021-03-22,technical issue,"[product, setup]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],"[social, medium]",2023-06-01 12:15:36,2023-06-01 17:14:42,3.0
1,2021-05-22,technical issue,"[peripheral, compatibility]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],[chat],2023-06-01 16:45:38,2023-06-01 17:14:42,3.0
2,2020-07-14,technical issue,"[network, problem]","[im, face, problem, productpurchased, productp...",[close],"[case, maybe, show, recently, computer, follow]",[low],"[social, medium]",2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,2020-11-13,billing inquiry,"[account, access]","[im, issue, productpurchased, please, assist, ...",[close],"[try, capital, clearly, never, color, toward, ...",[low],"[social, medium]",2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,2020-02-04,billing inquiry,"[data, loss]","[im, issue, productpurchased, please, assist, ...",[close],"[west, decision, evidence, bit]",[low],[email],2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

Remove Stopwords

In [38]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))
for cat in cat_cols_t:
  df[cat]=df[cat].apply(lambda x:[word for word in x if word not in stop_words ])
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,2021-03-22,technical issue,"[product, setup]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],"[social, medium]",2023-06-01 12:15:36,2023-06-01 17:14:42,3.0
1,2021-05-22,technical issue,"[peripheral, compatibility]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],[chat],2023-06-01 16:45:38,2023-06-01 17:14:42,3.0
2,2020-07-14,technical issue,"[network, problem]","[im, face, problem, productpurchased, productp...",[close],"[case, maybe, show, recently, computer, follow]",[low],"[social, medium]",2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,2020-11-13,billing inquiry,"[account, access]","[im, issue, productpurchased, please, assist, ...",[close],"[try, capital, clearly, never, color, toward, ...",[low],"[social, medium]",2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,2020-02-04,billing inquiry,"[data, loss]","[im, issue, productpurchased, please, assist, ...",[close],"[west, decision, evidence, bit]",[low],[email],2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

applying lemataizaton

In [39]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

# Download necessary components
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')

lemmatizer = WordNetLemmatizer()

# Helper function to map NLTK POS tags to WordNet tags
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ, "N": wordnet.NOUN, "V": wordnet.VERB, "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

# Apply lemmatization with POS tagging
for cat in cat_cols_t:
    df[cat] = df[cat].apply(lambda x: [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in x])
df.tail()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
8464,2021-12-08,product inquiry,"[installation, support]","[productpurchased, make, strange, noise, funct...",[open],"[former, wrong, interview, heart, leg]",[low],[phone],2023-06-01 01:21:19,2023-06-01 17:14:42,3.0
8465,2020-02-22,technical issue,"[refund, request]","[im, issue, productpurchased, please, assist, ...",[open],"[former, wrong, interview, heart, leg]",[critical],[email],2023-06-01 01:21:19,2023-06-01 17:14:42,3.0
8466,2021-08-17,technical issue,"[account, access]","[im, issue, productpurchased, please, assist, ...",[close],"[eight, account, century, nature, kitchen]",[high],"[social, medium]",2023-06-01 09:44:22,2023-06-01 04:31:22,3.0
8467,2021-10-16,product inquiry,"[payment, issue]","[im, issue, productpurchased, please, assist, ...",[close],"[seat, culture, plan]",[medium],[email],2023-06-01 18:28:24,2023-06-01 05:32:24,3.0
8468,2020-06-01,billing inquiry,"[hardware, issue]","[seem, hardware, problem, productpurchased, sc...",[open],"[former, wrong, interview, heart, leg]",[high],[phone],2023-06-01 01:21:19,2023-06-01 17:14:42,3.0

remove nan values in the data

In [40]:
# Replace empty lists with a list containing 'none'
for cat in cat_cols_t:
    df[cat] = df[cat].apply(lambda x: ['none'] if len(x) == 0 else x)
df.head()

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,2021-03-22,technical issue,"[product, setup]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],"[social, medium]",2023-06-01 12:15:36,2023-06-01 17:14:42,3.0
1,2021-05-22,technical issue,"[peripheral, compatibility]","[im, issue, productpurchased, please, assist, ...","[pending, customer, response]","[former, wrong, interview, heart, leg]",[critical],[chat],2023-06-01 16:45:38,2023-06-01 17:14:42,3.0
2,2020-07-14,technical issue,"[network, problem]","[im, face, problem, productpurchased, productp...",[close],"[case, maybe, show, recently, computer, follow]",[low],"[social, medium]",2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,2020-11-13,billing inquiry,"[account, access]","[im, issue, productpurchased, please, assist, ...",[close],"[try, capital, clearly, never, color, toward, ...",[low],"[social, medium]",2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,2020-02-04,billing inquiry,"[data, loss]","[im, issue, productpurchased, please, assist, ...",[close],"[west, decision, evidence, bit]",[low],[email],2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

Text vectorization

In [32]:
#for text vectorization we have to join the words
for cat in cat_cols:
  df[cat]=df[cat].apply(lambda x: ' '.join(x))
df.head()

,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,2021-03-22,technical issue,product setup,im issue productpurchased please assist billin...,pending customer response,former wrong interview heart leg,critical,social medium,2023-06-01 12:15:36,2023-06-01 17:14:42,3.0
1,2021-05-22,technical issue,peripheral compatibility,im issue productpurchased please assist need c...,pending customer response,former wrong interview heart leg,critical,chat,2023-06-01 16:45:38,2023-06-01 17:14:42,3.0
2,2020-07-14,technical issue,network problem,im face problem productpurchased productpurcha...,close,case maybe show recently computer follow,low,social medium,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,2020-11-13,billing inquiry,account access,im issue productpurchased please assist proble...,close,try capital clearly never color toward story,low,social medium,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,2020-02-04,billing inquiry,data loss,im issue productpurchased please assist note s...,close,west decision evidence bit,low,email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [42]:
# Convert lists of words back into single strings
for cat in cols_to_use:
    df[cat] = df[cat].apply(lambda x: ' '.join(x) if isinstance(x, list) else str(x))

In [49]:
# If training for Ticket Type, drop 'Ticket Priority'
cols_to_use = ['Ticket Channel', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution']
df_temp = df.drop(columns=['Ticket Priority'], errors='ignore')

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

vectorizer = TfidfVectorizer(stop_words='english',ngram_range=(1,3),max_features=5000)
tfidf_matrices = []

# This now uses the list that DOES NOT contain 'Ticket Priority'
for cat in cols_to_use:
    matrix = vectorizer.fit_transform(df_temp[cat])
    tfidf_matrices.append(matrix)

X = hstack(tfidf_matrices)
print(f"Final feature matrix shape: {X.shape}")

Final feature matrix shape: (8469, 10055)

In [60]:
df['Ticket Priority'].unique()

array(['critical', 'low', 'high', 'medium'], dtype=object)

In [61]:
df['Ticket Type'].unique()

array(['technical issue', 'billing inquiry', 'cancellation request',
       'product inquiry', 'refund request'], dtype=object)

split the data for ticket priority , type and trtain the model

for ticket priority

In [68]:
# Import the Classifier versions
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import LabelEncoder
# Use the X that was created from df_temp
y = df['Ticket Priority']
le=LabelEncoder()
y=le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model_p = XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1)
model_p.fit(X_train, y_train)
y_pred = model_p.predict(X_test)

for ticket type

In [83]:
# Use the X that was created from df_temp
y_tic = df['Ticket Type']
y_tic=le.fit_transform(y_tic)
model_t = LGBMClassifier()
X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(X, y_tic, test_size=0.2, random_state=42)
model_t.fit(X_train_t, y_train_t)
y_pred_t = model_t.predict(X_test_t)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.041481 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 81345
[LightGBM] [Info] Number of data points in the train set: 6775, number of used features: 1352
[LightGBM] [Info] Start training from score -1.668726
[LightGBM] [Info] Start training from score -1.599890
[LightGBM] [Info] Start training from score -1.631827
[LightGBM] [Info] Start training from score -1.571780
[LightGBM] [Info] Start training from score -1.578197

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Evaluation for model

In [84]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.2526564344746163
              precision    recall  f1-score   support

           0       0.24      0.24      0.24       411
           1       0.25      0.22      0.23       409
           2       0.23      0.20      0.22       415
           3       0.28      0.34      0.31       459

    accuracy                           0.25      1694
   macro avg       0.25      0.25      0.25      1694
weighted avg       0.25      0.25      0.25      1694

In [85]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test_t,y_pred_t))
print(classification_report(y_test_t,y_pred_t))

0.20425029515938606
              precision    recall  f1-score   support

           0       0.17      0.14      0.16       357
           1       0.20      0.21      0.20       327
           2       0.19      0.20      0.20       316
           3       0.20      0.21      0.20       345
           4       0.25      0.26      0.26       349

    accuracy                           0.20      1694
   macro avg       0.20      0.20      0.20      1694
weighted avg       0.20      0.20      0.20      1694